import test from 'node:test';
import assert from 'node:assert/strict';
import { createVisualAssetLibrary } from '../../plugin/domain/visual-asset-library.js';
const png = Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0,0,0,13,0x49,0x48,0x44,0x52,0,0,0,2,0,0,0,2,8,6]);
function library() { const files = new Map(); return { files, async put(id, format, data) { files.set(`${id}.${format}`, Buffer.from(data)); }, async remove(id, format) { files.delete(`${id}.${format}`); }, async resolveAssetPath(id, format) { return `visual-assets/${id}.${format}`; } }; }
test('imports immutable metadata and deduplicates by SHA256', async () => { const storage = library(); const assets = createVisualAssetLibrary({ storage }); const first = await assets.importBuffer({ name:'mint.png', kind:'icon', buffer:png, tags:['mint',' icon '] }); const second = await assets.importBuffer({ name:'copy.png', kind:'icon', buffer:Buffer.from(png), tags:[] }); assert.equal(second.assetId, first.assetId); assert.equal(storage.files.size, 1); assert.deepEqual(first.tags, ['mint','icon']); assert.equal(first.references, 0); assert.throws(() => { first.name = 'changed'; }, TypeError); });
test('tracks structured references and protects deletion', async () => { const storage = library(); const assets = createVisualAssetLibrary({ storage }); const asset = await assets.importBuffer({ name:'mint.png', kind:'decoration', buffer:png }); await assets.addReference(asset.assetId, { ownerType:'profile', ownerId:'default', slot:'icon' }); await assets.addReference(asset.assetId, { ownerType:'profile', ownerId:'default', slot:'icon' }); assert.deepEqual(assets.references(asset.assetId), [{ ownerType:'profile', ownerId:'default', slot:'icon' }]); await assert.rejects(() => assets.remove(asset.assetId), (error) => error.code === 'VISUAL_ASSET_IN_USE' && error.details.references.length === 1); assert.equal(assets.removeReference(asset.assetId, { ownerType:'profile', ownerId:'default', slot:'icon' }), true); assert.equal(await assets.remove(asset.assetId), true); assert.equal(storage.files.size, 0); });
test('lists by search and kind', async () => { const storage = library(); const assets = createVisualAssetLibrary({ storage }); await assets.importBuffer({ name:'Mint Star.png', kind:'particle', buffer:png, tags:['star'] }); assert.equal(assets.list({ search:'star', kind:'particle' }).length, 1); assert.equal(assets.list({ kind:'avatar' }).length, 0); });
test('restores a validated snapshot and rebuilds reference counts', async () => { const storage = library(); const source = createVisualAssetLibrary({ storage }); const asset = await source.importBuffer({ assetId:'asset-restored', name:'mint.png', kind:'icon', buffer:png }); await source.addReference(asset.assetId, { ownerType:'profile', ownerId:'default', slot:'icon' }); const restored = createVisualAssetLibrary({ storage }); assert.deepEqual(restored.restoreSnapshot(source.snapshot()), { assetCount:1 }); assert.equal(restored.get(asset.assetId).references, 1); assert.deepEqual(restored.references(asset.assetId), [{ ownerType:'profile', ownerId:'default', slot:'icon' }]); assert.throws(() => restored.restoreSnapshot({ version:1, assets:[{ ...asset, format:'svg' }], references:{} }), { code:'VISUAL_ASSET_SNAPSHOT_INVALID' }); });
