function escapeHtml(value) {
  return String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
}

export function renderEventPresentationSettingsFragment(initialData = null) {
  const boot = initialData && typeof initialData === 'object' ? initialData : { rows: [], settings: {} };
  const bootJson = JSON.stringify(boot).replaceAll('<', '\\u003c');
  return `<style data-settings-view-style>
.event-presentation-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,.7fr);gap:16px;align-items:start}.event-presentation-panel{border:1px solid var(--line);border-radius:10px;background:var(--surface);padding:20px}.event-presentation-panel h2{margin:0;font-size:18px}.event-presentation-intro{margin:7px 0 18px;color:var(--muted);font-size:13px}.event-presentation-table{width:100%;border-collapse:collapse;font-size:13px}.event-presentation-table th,.event-presentation-table td{padding:10px 8px;text-align:left;border-top:1px solid rgba(48,71,64,.7);vertical-align:top}.event-presentation-table th{color:var(--muted);font-weight:700}.event-presentation-tag{display:inline-flex;padding:3px 7px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:11px}.event-presentation-help{margin:0;color:var(--muted);font-size:12px;line-height:1.7}.event-presentation-feedback{min-height:24px;margin-top:12px;color:var(--muted)}.event-presentation-feedback.success{color:var(--success)}.event-presentation-feedback.error{color:var(--danger)}@media(max-width:760px){.event-presentation-grid{grid-template-columns:1fr}.event-presentation-panel{padding:16px}.event-presentation-table{display:block;overflow:auto}}
</style>
<div class="event-presentation-grid" data-settings-view-root="events">
<section class="event-presentation-panel"><h2>事件目录与表现绑定</h2><p class="event-presentation-intro">每个事件只有一个主身份，可以独立绑定声音、视觉和行为通道。相同通道共同作用，不同通道互不干扰。</p><table class="event-presentation-table"><thead><tr><th>事件</th><th>大类</th><th>当前绑定层</th><th>声音 / 视觉 / 行为</th></tr></thead><tbody id="event-presentation-rows"></tbody></table><div id="event-presentation-feedback" class="event-presentation-feedback" role="status" aria-live="polite"></div></section>
<aside class="event-presentation-panel"><h2>重要性关键词</h2><p class="event-presentation-intro">默认是普通。卡片内容命中关键词后标记为重要，不改变事件身份。</p><textarea id="event-presentation-keywords" rows="8" style="width:100%;box-sizing:border-box;border:1px solid var(--line);border-radius:6px;padding:8px;background:var(--surface-raised);color:var(--text)" aria-label="重要性关键词"></textarea><button id="event-presentation-save" type="button" style="margin-top:12px;min-height:36px;border:1px solid var(--accent-strong);border-radius:6px;padding:7px 14px;background:var(--accent-strong);color:var(--accent-ink);cursor:pointer;font-weight:700">保存关键词</button><p class="event-presentation-help" style="margin-top:14px">绑定编辑器将在事件模型和 Profile 迁移完成后逐步开放。当前页面先提供目录、继承层级和关键词设置，避免让 UI 复制后端规则。</p></aside>
</div>
<script>
(function(){var boot=${bootJson};var rows=document.getElementById('event-presentation-rows');var feedback=document.getElementById('event-presentation-feedback');var keywords=document.getElementById('event-presentation-keywords');function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}function render(data){var list=data&&Array.isArray(data.rows)?data.rows:[];rows.innerHTML=list.map(function(row){var b=row.binding||{};return '<tr><td><strong>'+esc(row.label)+'</strong><br><span class="event-presentation-tag">'+esc(row.eventId)+'</span></td><td>'+esc(row.categoryId)+'</td><td>'+esc(row.matchedBy||'global')+'</td><td>'+esc(b.soundProfileId)+'<br>'+esc(b.visualProfileId)+'<br>'+esc(b.behaviorProfileId)+' · '+esc(b.behaviorChannelId)+'</td></tr>';}).join('');var ks=data&&data.settings&&data.settings.importanceKeywords&&data.settings.importanceKeywords.keywords||[];keywords.value=ks.join('\n');}function request(url,opt){return (window.hana&&window.hana.api&&window.hana.api.fetch?window.hana.api.fetch(url,opt):fetch(url,opt)).then(function(r){return r.text().then(function(t){var d;try{d=JSON.parse(t);}catch(e){d={};}if(!r.ok)throw new Error(d.error&&d.error.message||'事件表现设置请求失败');return d;});});}document.getElementById('event-presentation-save').addEventListener('click',function(){feedback.textContent='正在保存…';feedback.className='event-presentation-feedback';request('event-presentation-settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({importanceKeywords:{keywords:keywords.value.split(/\n|,/).map(function(v){return v.trim();}).filter(Boolean)}})}).then(function(data){render(data);feedback.textContent='已保存并应用';feedback.className='event-presentation-feedback success';}).catch(function(error){feedback.textContent=error.message;feedback.className='event-presentation-feedback error';});});render(boot);})();
</script>`;
}
